services:
  app-auth:
    build:
      dockerfile: 'Dockerfile'
    container_name: kpo-auth
    expose:
      - '8081'
    ports:
      - '8081:8081'
    depends_on:
      - postgres-auth
    environment:
      - DB_URL=jdbc:postgresql://postgres-auth:5432/kpo-hw-3-auth
  postgres-auth:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kpo-hw-3-auth'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=erentsen'
    ports:
      - '5432:5432'
  app-shop:
    build:
      context: '../kpo-hw-3-shop'
      dockerfile: '../kpo-hw-3-shop/Dockerfile'
    container_name: kpo-shop
    expose:
      - '8080'
    ports:
      - '8080:8080'
    depends_on:
      - postgres-shop
      - app-auth
    environment:
      - DB_URL=jdbc:postgresql://postgres-shop:5432/kpo-hw-3-shop
      - AUTH_host=app-auth
  postgres-shop:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kpo-hw-3-shop'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=erentsen'
    ports:
      - '5433:5432'
