services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kpo-hw-3-auth'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=erentsen'
    ports:
      - '5432'
